### ISSUE TITLE
About the accuracy for different loss on RAF-DB

### ISSUE THREAD

**Issue by wbb95** [sugar2019/facial-expression-recognition-in-wild-datasets#1]
Dear　sugar2019 :
Thanks for your work , i interest in your work --About the accuracy for different loss on RAF-DB,i hope your reply,so thanks!

**Comment by sugar2019** [comment]
smSelf         0.7657
wSm            0.7717
wSmCl         0.7657
wSmIsland   0.7771
wSmEce       0.7643
wSmLce       0.7686
 
All results are the mean accuracy of the diagonal value of confusion matrix! Thank you for your attention.

**Comment by wbb95** [comment]
thanks a lot .

**Comment by wbb95** [comment]
Thanks a lot.
